// 多会话拆分服务层 barrel（docs/0820/session-split）。
export {
  archiveConversationForUserSync,
  backfillLegacyConversationsSync,
  buildConversationSummary,
  createConversationForUserSync,
  listConversationsForChannelForUserSync,
  listConversationsForEmployeeForUserSync,
  readConversationForUserSync,
  recordConversationMessageActivitySync,
  refreshConversationSummaryAfterReplySync,
  resolveConversationLaneForSendSync,
  unarchiveConversationForUserSync,
  updateConversationSummaryForUserSync,
  type BackfillLegacyConversationsResult,
  type CreateConversationForUserInput,
  type CreateConversationForUserResult,
  type ListConversationsForChannelForUserInput,
  type ListConversationsForUserInput,
  type ReadConversationForUserInput,
  type RecordConversationMessageActivityInput,
  type RefreshConversationSummaryAfterReplyInput,
  type ResolveConversationLaneForSendInput,
  type UpdateConversationSummaryForUserInput,
} from "./conversations.ts";
