import {
  registerIntegrationProviderAdapter,
  type IntegrationProviderAdapter,
} from "../../core/index.ts";
import { feishuIntegrationProviderAdapter } from "./adapter.ts";

export {
  FEISHU_AGENT_BOT_REQUIRED_CREDENTIAL_FIELDS,
  FEISHU_BOT_SMOKE_SCOPES,
  FEISHU_DATA_PLANE_SMOKE_SCOPES,
  FEISHU_DEFAULT_SCOPES,
  FEISHU_EVENT_CALLBACK_PATH,
  FEISHU_EVENT_CALLBACK_REQUIRED_CREDENTIAL_FIELDS,
  FEISHU_FINAL_EVIDENCE_GATE_REQUIREMENTS,
  FEISHU_OPEN_PLATFORM_CONSOLE_URLS,
  FEISHU_OPEN_PLATFORM_SETUP_STEPS,
  FEISHU_OPENAPI_REQUIRED_DESTRUCTIVE_LIVE_SMOKE_STEPS,
  FEISHU_OPENAPI_REQUIRED_LIVE_SMOKE_STEPS,
  FEISHU_OPENAPI_REQUIRED_REQUEST_STEPS,
  FEISHU_PROVIDER_DESCRIPTOR,
  FEISHU_PROVIDER_ID,
  FEISHU_RECOMMENDED_CREDENTIAL_FIELDS,
  FEISHU_REQUIRED_CREDENTIAL_FIELDS,
  FEISHU_REQUIRED_EVENTS,
} from "./constants.ts";
export {
  checkFeishuAgentBotHealth,
  createFeishuAgentBotBindingSync,
  disableFeishuAgentBotBindingSync,
  isFeishuAgentBotBinding,
  listFeishuAgentBotBindingsSync,
  readFeishuAgentBotBindingByAgentSync,
  resolveFeishuAgentBotBindingSync,
  rotateFeishuAgentBotCredentialsSync,
  updateFeishuAgentBotPolicySync,
  type FeishuAgentBotChannelAutoProvisioningInput,
  type FeishuAgentBotExternalGuestPolicyInput,
  type CreateFeishuAgentBotBindingInput,
  type DisableFeishuAgentBotBindingInput,
  type FeishuAgentBotBinding,
  type FeishuAgentBotHealthCheckResult,
  type RotateFeishuAgentBotCredentialsInput,
  type UpdateFeishuAgentBotPolicyInput,
} from "./agent-bot-bindings.ts";
export {
  ensureFeishuAgentMentionText,
  isFeishuBotAddedToChatPayload,
  resolveFeishuAgentBotRouteSync,
  resolveFeishuChatDescriptor,
  type FeishuAgentBotRoute,
  type FeishuChatDescriptor,
} from "./agent-bot-routing.ts";
export {
  queueFeishuChannelAutoProvisionConfirmationOutboxSync,
  queueFeishuChannelSetupCardOutboxSync,
  readFeishuChannelBindingReviewStatus,
  readFeishuChannelAutoProvisionPolicy,
  resolveOrProvisionFeishuChannelBindingSync,
  shouldAutoProvisionFeishuChannelForBotAdded,
  shouldAutoProvisionFeishuChannelForFirstMessage,
  type FeishuChannelAutoProvisionPolicy,
  type FeishuChannelAutoProvisionResult,
} from "./channel-auto-provisioning.ts";
export {
  buildFeishuExternalGuestActor,
  ensureFeishuExternalGuestChannelActorSync,
  evaluateFeishuExternalGuestPolicy,
  readFeishuExternalParticipantPolicy,
  FEISHU_EXTERNAL_GUEST_DISPLAY_NAME,
  type FeishuExternalGuestActor,
  type FeishuExternalGuestDecision,
  type FeishuExternalParticipantPolicy,
} from "./external-guests.ts";
export {
  listFeishuThreadBindingsForChatSync,
  readFeishuThreadBindingSync,
  recordFeishuThreadBindingSync,
  resolveFeishuThreadBindingKey,
  type ReadFeishuThreadBindingInput,
  type RecordFeishuThreadBindingInput,
} from "./thread-bindings.ts";
export {
  evaluateFeishuExternalGuestRuntimeToolIdentityRequirementFromTaskInput,
  type FeishuRuntimeToolIdentityRequirement,
} from "./runtime-tools.ts";
export {
  createFeishuApiClient,
  fetchFeishuTenantAccessToken,
  type FeishuApiClient,
  type FeishuApiRequest,
  type FeishuClientCredentials,
  type FeishuTenantAccessTokenResult,
} from "./client.ts";
export {
  readFeishuChatMemberSnapshot,
  resolveFeishuChatMemberDisplayName,
  type FeishuChatMemberSnapshot,
} from "./chat-members.ts";
export {
  buildEncryptedFeishuCredentials,
  readFeishuIntegrationCredentials,
  summarizeFeishuStoredCredentials,
  type FeishuPlainCredentials,
} from "./credentials.ts";
export {
  buildFeishuHealthSnapshotConfigJson,
  checkFeishuIntegrationHealth,
  readFeishuAppScopes,
  readFeishuBotInfo,
  type FeishuHealthCheckResult,
  type FeishuScopeReadiness,
} from "./health.ts";
export {
  feishuIntegrationProviderAdapter,
} from "./adapter.ts";
export {
  buildFeishuUrlVerificationResponse,
  decryptFeishuEventPayload,
  isFeishuEncryptedPayload,
  isFeishuApprovalCardActionCallbackPayload,
  isFeishuCardActionCallbackPayload,
  isFeishuUrlVerificationPayload,
  resolveFeishuCallbackAppId,
  resolveFeishuCallbackTenantKey,
  resolveFeishuEventId,
  resolveFeishuEventReceivedAt,
  resolveFeishuEventType,
  validateFeishuCallbackContext,
  verifyFeishuCallbackToken,
  verifyFeishuRequestSignature,
  type FeishuCallbackContextValidationResult,
  type FeishuEventHeader,
  type FeishuEncryptedPayload,
  type FeishuEventPayload,
  type FeishuUrlVerificationPayload,
} from "./events.ts";
export {
  normalizeFeishuChannelSdkMessage,
  normalizeFeishuInboundMessage,
  type FeishuChannelSdkMentionInfo,
  type FeishuChannelSdkNormalizedMessage,
  type FeishuChannelSdkResourceDescriptor,
} from "./normalize-message.ts";
export {
  processFeishuInboundEvent,
  processFeishuInboundEventSync,
  recordFeishuCardActionCallbackIgnoredSync,
  recordFeishuCallbackRejectedSync,
  recordFeishuInboundEventSync,
  type FeishuInboundDispatchStatus,
  type FeishuInboundProcessResult,
  type FeishuInboundRecordResult,
} from "./inbound.ts";
export {
  FEISHU_INBOUND_ATTACHMENT_MAX_BYTES,
  FEISHU_INBOUND_ATTACHMENT_TIMEOUT_MS,
  buildFeishuMessageResourceRequest,
  createFeishuInboundAttachmentDownloader,
  downloadFeishuInboundMessageAttachment,
  resolveFeishuInboundAttachmentDescriptor,
  type FeishuInboundAttachmentDescriptor,
  type FeishuInboundAttachmentDownloadInput,
  type FeishuInboundAttachmentDownloader,
  type FeishuInboundMessageResourceType,
} from "./attachments.ts";
export {
  FEISHU_OUTBOX_MAX_ATTEMPTS,
  FEISHU_OUTBOUND_ATTACHMENT_MAX_BYTES,
  FEISHU_TEXT_MESSAGE_MAX_BYTES,
  buildFeishuAgentThreadCollaborationCard,
  buildFeishuAgentStatusCard,
  buildFeishuAgentStatusCardOutboundMessage,
  buildFeishuAttachmentOutboundMessage,
  buildFeishuFileUploadRequest,
  buildFeishuImageUploadRequest,
  buildFeishuIdentityBindingRequiredCard,
  buildFeishuInteractiveCardOutboundMessage,
  buildFeishuMessageCreateRequest,
  buildFeishuOutboundMessagePolicyInput,
  buildFeishuTextOutboundMessage,
  buildFeishuTextOutboundMessages,
  computeFeishuOutboxNextAttemptAt,
  computeFeishuOutboxRetryDelaySeconds,
  decideFeishuOutboundMessagePolicy,
  drainFeishuOutboxMessages,
  formatFeishuOutboundError,
  normalizeFeishuOutboundError,
  processDueFeishuOutboxMessages,
  processFeishuOutboxMessage,
  queueFeishuAgentStatusCardOutboxSync,
  queueFeishuChannelReplyOutboxSync,
  queueFeishuOutboundMessageSync,
  resolveFeishuOutboundFileKey,
  resolveFeishuOutboundImageKey,
  resolveFeishuOutboundMessageId,
  sendFeishuOutboxPayload,
  sendFeishuAttachmentOutboxPayload,
  splitFeishuTextMessageChunks,
  uploadFeishuOutboundAttachment,
  type FeishuOutboundMessagePolicyResult,
  type FeishuOutboundAttachmentPayload,
  type FeishuOutboundAttachmentRef,
  type FeishuApprovalCardActionPayload,
  type FeishuAgentStatusCardStatus,
  type FeishuOutboundErrorInfo,
  type FeishuOutboxDrainResult,
  type FeishuOutboxProcessResult,
} from "./outbound.ts";
export {
  buildFeishuDataOperationApprovalMetadata,
  createFeishuDataOperationApprovalRequestSync,
  executeFeishuDataOperationWithApproval,
  planBoundFeishuWriteDataOperationWithApproval,
  processFeishuCardActionCallback,
  reviewFeishuDataOperationApproval,
  sanitizeFeishuDataOperationApprovalMetadata,
  type FeishuCardActionCallbackResult,
  type FeishuDataOperationApprovalContext,
  type FeishuDataOperationApprovalMetadata,
  type FeishuDataOperationWithApprovalResult,
} from "./approval.ts";
export {
  executeApprovedFeishuDataOperation,
  executeBoundFeishuReadDataOperation,
  executeFeishuDataOperation,
  FEISHU_DATA_OPERATION_DESCRIPTORS,
  feishuDocumentProviderAdapter,
  planBoundFeishuWriteDataOperation,
  validateApprovedFeishuDataOperationBinding,
  validateApprovedFeishuDataOperationRun,
  validateFeishuDofeAgentResourceAccessForDataOperation,
  validateFeishuResourceBindingScopes,
  validateFeishuResourceBindingForDataOperation,
  type FeishuDofeAgentResourceAccessDependencies,
  type FeishuDofeAgentResourceAccessValidationResult,
  type FeishuApprovedDataOperationBindingValidationResult,
  type FeishuApprovedDataOperationValidationResult,
  type FeishuBoundDataOperationActor,
  type FeishuResourceBindingScopeValidationResult,
  type FeishuResourceBindingValidationResult,
} from "./data-plane.ts";
export {
  buildFeishuBlockedOperationResult,
  buildFeishuDataOperationPayloadHash,
  buildFeishuDataOperationPolicyInput,
  buildFeishuReadOperationRequest,
  buildFeishuWriteOperationRequest,
  planFeishuDataOperation,
  sanitizeFeishuOperationResponseSummary,
  summarizeFeishuDataOperationResponse,
  summarizeFeishuDataOperationRequest,
  summarizeFeishuOperationResponse,
  type FeishuDataOperationPlan,
  type FeishuDataOperationPolicyDecision,
} from "./operation-plan.ts";
export {
  resolveFeishuResourceDescriptor,
  resolveFeishuResourceDescriptorForType,
  validateFeishuResourceDescriptorForBinding,
  type FeishuResourceDescriptorBindingValidationResult,
} from "./resource-resolver.ts";
export {
  summarizeFeishuResourceMetadataSnapshot,
  syncFeishuResourceMetadataSnapshotSync,
  syncFeishuResourceMetadataSnapshotFromResultSync,
  syncFeishuDataTablePreviewFromReadResultSync,
  upsertFeishuExternalDataTableSync,
  upsertFeishuExternalChannelDocumentSync,
  type FeishuDataTablePreviewSyncResult,
  type FeishuResourceMetadataSnapshot,
  type FeishuResourceMetadataSyncResult,
  type FeishuExternalChannelDocumentInput,
  type FeishuExternalChannelDocumentSyncResult,
  type FeishuExternalDataTableInput,
  type FeishuExternalDataTableSyncResult,
} from "./dofe-agent-sync.ts";
export {
  resolveFeishuDocResource,
} from "./docs.ts";
export {
  resolveFeishuSheetResource,
} from "./sheets.ts";
export {
  resolveFeishuBaseResource,
} from "./base.ts";
export {
  DEFAULT_FEISHU_LARK_CLI_COMMAND,
  FEISHU_LARK_CLI_EXECUTOR_ENV_NAMES,
  FEISHU_LARK_CLI_MANIFEST_SCHEMA_VERSION,
  FEISHU_LARK_CLI_OPERATION_MANIFEST_KIND,
  FEISHU_LARK_CLI_RESULT_MANIFEST_KIND,
  FEISHU_LARK_CLI_RESULT_MANIFEST_RELATIVE_PATH,
  buildFeishuLarkCliAllowedShellPatterns,
  buildFeishuLarkCliDiagnosticRuntimeToolCapability,
  buildFeishuLarkCliOperationManifest,
  buildFeishuLarkCliResourceGrantFromBinding,
  buildFeishuLarkCliRuntimeToolCapability,
  diagnoseFeishuLarkCliRuntime,
  isFeishuLarkCliRuntimeEnabled,
  listFeishuLarkCliResourceGrantsForChannelSync,
  resolveFeishuLarkCliCommand,
  resolveFeishuLarkCliOperationKind,
  summarizeFeishuLarkCliResultManifest,
  type BuildFeishuLarkCliOperationManifestInput,
  type BuildFeishuLarkCliRuntimeToolCapabilityInput,
  type DiagnoseFeishuLarkCliRuntimeInput,
  type FeishuLarkCliOperationKind,
  type FeishuLarkCliOperationManifest,
  type FeishuLarkCliOperationManifestResourceGrant,
  type FeishuLarkCliResourceGrant,
  type FeishuLarkCliRuntimeDiagnostic,
  type FeishuLarkCliRuntimeReadinessStatus,
} from "./lark-cli.ts";
export {
  FEISHU_RUNTIME_DATA_OPERATION_REQUESTS_KIND,
  FEISHU_RUNTIME_DATA_OPERATION_REQUESTS_RELATIVE_PATH,
  FEISHU_RUNTIME_DATA_OPERATION_REQUESTS_SCHEMA_VERSION,
  appendFeishuRuntimeDataOperationRequest,
  applyFeishuLarkCliResultManifestOperations,
  applyFeishuRuntimeDataOperationRequests,
  readFeishuRuntimeDataOperationRequestsManifest,
  type FeishuLarkCliResultManifestOperationSummary,
  type FeishuRuntimeDataOperationRequestApplySummary,
  type FeishuRuntimeDataOperationRequestManifestEntry,
  type FeishuRuntimeDataOperationRequestsManifest,
} from "./runtime-output.ts";
export {
  buildFeishuWebSocketEventPayload,
  processFeishuWebSocketEvent,
  startFeishuWebSocketWorker,
  startFeishuWebSocketWorkerSupervisor,
  type FeishuWebSocketEventProcessorDependencies,
  type FeishuWebSocketWorkerDependencies,
  type FeishuWebSocketWorkerError,
  type FeishuWebSocketWorkerHandle,
  type FeishuWebSocketWorkerSupervisorHandle,
  type FeishuWebSocketWorkerIntegrationSummary,
  type FeishuWebSocketWorkerMetrics,
  type FeishuWebSocketWorkerSession,
  type FeishuWebSocketWorkerSessionFactory,
  type FeishuWebSocketWorkerSessionFactoryInput,
  type FeishuWebSocketWorkerSummary,
} from "./websocket-worker.ts";

export function registerFeishuIntegrationProvider(): IntegrationProviderAdapter {
  registerIntegrationProviderAdapter(feishuIntegrationProviderAdapter);
  return feishuIntegrationProviderAdapter;
}
