// 域 barrel：从 src/index.ts 拆出（3.7-7），供 `@dofe-agent/services/integrations` 子路径与根 re-export 使用。

export {
  IntegrationProviderError,
  clearIntegrationProviderAdaptersForTests,
  createIntegrationProviderError,
  enqueueExternalOutboundMessageSync,
  listDueExternalOutboundMessagesSync,
  listIntegrationProviderAdapters,
  readIntegrationProviderAdapter,
  recordExternalDataOperationFinishSync,
  recordExternalDataOperationPlanSync,
  recordExternalDataOperationStartSync,
  registerIntegrationProviderAdapter,
  type DofeAgentOutboundMessage,
  type ExternalDataOperationRequest,
  type ExternalDataOperationResult,
  type ExternalDocumentProviderAdapter,
  type ExternalMessageAttachment,
  type ExternalMessageEnvelope,
  type ExternalOutboundMessagePayload,
  type ExternalResourceDescriptor,
  type ExternalResourceOperationDescriptor,
  type IncomingMessageRequest,
  type IncomingMessageVerificationResult,
  type IntegrationCapability,
  type IntegrationProviderAdapter,
  type IntegrationProviderDescriptor,
  type IntegrationRuntimeContext,
  type MessageTransportAdapter,
} from "./core/index.ts";

export {
  FEISHU_DATA_OPERATION_DESCRIPTORS,
  FEISHU_AGENT_BOT_REQUIRED_CREDENTIAL_FIELDS,
  FEISHU_BOT_SMOKE_SCOPES,
  FEISHU_DATA_PLANE_SMOKE_SCOPES,
  FEISHU_DEFAULT_SCOPES,
  FEISHU_EVENT_CALLBACK_PATH,
  FEISHU_EVENT_CALLBACK_REQUIRED_CREDENTIAL_FIELDS,
  FEISHU_FINAL_EVIDENCE_GATE_REQUIREMENTS,
  FEISHU_OPEN_PLATFORM_CONSOLE_URLS,
  FEISHU_OPEN_PLATFORM_SETUP_STEPS,
  FEISHU_OPENAPI_REQUIRED_DESTRUCTIVE_LIVE_SMOKE_STEPS,
  FEISHU_OPENAPI_REQUIRED_LIVE_SMOKE_STEPS,
  FEISHU_OPENAPI_REQUIRED_REQUEST_STEPS,
  FEISHU_LARK_CLI_EXECUTOR_ENV_NAMES,
  FEISHU_LARK_CLI_MANIFEST_SCHEMA_VERSION,
  FEISHU_LARK_CLI_OPERATION_MANIFEST_KIND,
  FEISHU_LARK_CLI_RESULT_MANIFEST_KIND,
  FEISHU_LARK_CLI_RESULT_MANIFEST_RELATIVE_PATH,
  FEISHU_RUNTIME_DATA_OPERATION_REQUESTS_KIND,
  FEISHU_RUNTIME_DATA_OPERATION_REQUESTS_RELATIVE_PATH,
  FEISHU_RUNTIME_DATA_OPERATION_REQUESTS_SCHEMA_VERSION,
  FEISHU_OUTBOX_MAX_ATTEMPTS,
  FEISHU_OUTBOUND_ATTACHMENT_MAX_BYTES,
  FEISHU_PROVIDER_DESCRIPTOR,
  FEISHU_PROVIDER_ID,
  FEISHU_RECOMMENDED_CREDENTIAL_FIELDS,
  FEISHU_REQUIRED_CALLBACK_SUBSCRIPTIONS,
  FEISHU_REQUIRED_CREDENTIAL_FIELDS,
  FEISHU_REQUIRED_EVENT_SUBSCRIPTIONS,
  FEISHU_REQUIRED_EVENTS,
  FEISHU_TEXT_MESSAGE_MAX_BYTES,
  resolveFeishuRequiredEventTypes,
  resolveFeishuEventSubscriptionSetupRequirements,
  DEFAULT_FEISHU_LARK_CLI_COMMAND,
  buildEncryptedFeishuCredentials,
  buildFeishuBlockedOperationResult,
  buildFeishuDataOperationApprovalMetadata,
  buildFeishuLarkCliAllowedShellPatterns,
  buildFeishuLarkCliDiagnosticRuntimeToolCapability,
  buildFeishuLarkCliOperationManifest,
  buildFeishuLarkCliResourceGrantFromBinding,
  buildFeishuLarkCliRuntimeToolCapability,
  appendFeishuRuntimeDataOperationRequest,
  applyFeishuLarkCliResultManifestOperations,
  applyFeishuRuntimeDataOperationRequests,
  buildFeishuAgentStatusCard,
  buildFeishuAgentStatusCardOutboundMessage,
  buildFeishuAttachmentOutboundMessage,
  buildFeishuHealthSnapshotConfigJson,
  buildFeishuIdentityBindingRequiredCard,
  buildFeishuFileUploadRequest,
  buildFeishuImageUploadRequest,
  buildFeishuInteractiveCardOutboundMessage,
  buildFeishuMessageCreateRequest,
  buildFeishuOutboundMessagePolicyInput,
  buildFeishuReadOperationRequest,
  buildFeishuTextOutboundMessage,
  buildFeishuTextOutboundMessages,
  buildFeishuUrlVerificationResponse,
  buildFeishuWebSocketEventPayload,
  buildFeishuExternalGuestActor,
  buildFeishuWriteOperationRequest,
  checkFeishuAgentBotHealth,
  checkFeishuIntegrationHealth,
  computeFeishuOutboxNextAttemptAt,
  computeFeishuOutboxRetryDelaySeconds,
  createFeishuAgentBotBindingSync,
  createFeishuInboundAttachmentDownloader,
  createFeishuDataOperationApprovalRequestSync,
  createFeishuApiClient,
  decryptFeishuEventPayload,
  diagnoseFeishuLarkCliRuntime,
  decideFeishuOutboundMessagePolicy,
  drainFeishuOutboxMessages,
  disableFeishuAgentBotBindingSync,
  inspectFeishuAgentBotBindingAvailabilitySync,
  ensureFeishuAgentMentionText,
  ensureFeishuExternalGuestChannelActorSync,
  evaluateFeishuExternalGuestRuntimeToolIdentityRequirementFromTaskInput,
  executeApprovedFeishuDataOperation,
  executeBoundFeishuReadDataOperation,
  executeFeishuDataOperation,
  executeFeishuDataOperationWithApproval,
  feishuDocumentProviderAdapter,
  feishuIntegrationProviderAdapter,
  fetchFeishuTenantAccessToken,
  formatFeishuOutboundError,
  FEISHU_EXTERNAL_GUEST_DISPLAY_NAME,
  isFeishuEncryptedPayload,
  isFeishuApprovalCardActionCallbackPayload,
  isFeishuAgentBotBinding,
  isFeishuBotAddedToChatPayload,
  isFeishuCardActionCallbackPayload,
  isFeishuUrlVerificationPayload,
  isFeishuLarkCliRuntimeEnabled,
  listFeishuAgentBotBindingsSync,
  listFeishuLarkCliResourceGrantsForChannelSync,
  listFeishuThreadBindingsForChatSync,
  normalizeFeishuOutboundError,
  normalizeFeishuInboundMessage,
  planBoundFeishuWriteDataOperation,
  planBoundFeishuWriteDataOperationWithApproval,
  planFeishuDataOperation,
  processFeishuCardActionCallback,
  processDueFeishuOutboxMessages,
  processFeishuInboundEvent,
  processFeishuInboundEventSync,
  processFeishuOutboxMessage,
  processFeishuWebSocketEvent,
  queueFeishuAgentStatusCardOutboxSync,
  queueFeishuChannelAutoProvisionConfirmationOutboxSync,
  readFeishuChatMemberSnapshot,
  resolveFeishuChatMemberDisplayName,
  queueFeishuChannelReplyOutboxSync,
  queueFeishuOutboundMessageSync,
  recordFeishuCardActionCallbackIgnoredSync,
  recordFeishuCallbackRejectedSync,
  recordFeishuThreadBindingSync,
  recordFeishuInboundEventSync,
  registerFeishuIntegrationProvider,
  readFeishuAppScopes,
  readFeishuAgentBotBindingByAgentSync,
  readFeishuBotInfo,
  readFeishuChannelAutoProvisionPolicy,
  readFeishuExternalParticipantPolicy,
  readFeishuIntegrationCredentials,
  readFeishuThreadBindingSync,
  reviewFeishuDataOperationApproval,
  rotateFeishuAgentBotCredentialsSync,
  updateFeishuAgentBotPolicySync,
  resolveFeishuCallbackAppId,
  resolveFeishuCallbackTenantKey,
  resolveFeishuBaseResource,
  resolveFeishuDocResource,
  resolveFeishuAgentBotBindingSync,
  resolveFeishuAgentBotRouteSync,
  resolveFeishuChatDescriptor,
  resolveFeishuEventId,
  resolveFeishuEventReceivedAt,
  resolveFeishuEventType,
  resolveFeishuLarkCliCommand,
  resolveFeishuLarkCliOperationKind,
  resolveFeishuOutboundFileKey,
  resolveFeishuOutboundImageKey,
  resolveFeishuOutboundMessageId,
  resolveFeishuResourceDescriptor,
  resolveFeishuResourceDescriptorForType,
  resolveFeishuSheetResource,
  resolveFeishuThreadBindingKey,
  resolveOrProvisionFeishuChannelBindingSync,
  sendFeishuOutboxPayload,
  sendFeishuAttachmentOutboxPayload,
  shouldAutoProvisionFeishuChannelForBotAdded,
  shouldAutoProvisionFeishuChannelForFirstMessage,
  splitFeishuTextMessageChunks,
  startFeishuWebSocketWorker,
  startFeishuWebSocketWorkerSupervisor,
  syncFeishuDataTablePreviewFromReadResultSync,
  syncFeishuResourceMetadataSnapshotSync,
  syncFeishuResourceMetadataSnapshotFromResultSync,
  sanitizeFeishuDataOperationApprovalMetadata,
  sanitizeFeishuOperationResponseSummary,
  summarizeFeishuDataOperationResponse,
  summarizeFeishuDataOperationRequest,
  summarizeFeishuStoredCredentials,
  summarizeFeishuOperationResponse,
  summarizeFeishuLarkCliResultManifest,
  summarizeFeishuResourceMetadataSnapshot,
  upsertFeishuExternalDataTableSync,
  upsertFeishuExternalChannelDocumentSync,
  uploadFeishuOutboundAttachment,
  validateApprovedFeishuDataOperationRun,
  validateFeishuDofeAgentResourceAccessForDataOperation,
  validateFeishuResourceDescriptorForBinding,
  validateFeishuResourceBindingScopes,
  validateFeishuResourceBindingForDataOperation,
  validateFeishuCallbackContext,
  verifyFeishuCallbackToken,
  verifyFeishuRequestSignature,
  type BuildFeishuLarkCliRuntimeToolCapabilityInput,
  type BuildFeishuLarkCliOperationManifestInput,
  type CreateFeishuAgentBotBindingInput,
  type DisableFeishuAgentBotBindingInput,
  type DiagnoseFeishuLarkCliRuntimeInput,
  type FeishuApprovedDataOperationValidationResult,
  type FeishuAgentBotBinding,
  type FeishuAgentBotBindingAvailability,
  type FeishuAgentBotChannelAutoProvisioningInput,
  type FeishuAgentBotExternalGuestPolicyInput,
  type FeishuAgentBotHealthCheckResult,
  type FeishuAgentBotRoute,
  type FeishuBoundDataOperationActor,
  type FeishuApiClient,
  type FeishuApiRequest,
  type FeishuClientCredentials,
  type FeishuDataOperationPlan,
  type FeishuDataOperationPolicyDecision,
  type FeishuDataOperationApprovalContext,
  type FeishuDataOperationApprovalMetadata,
  type FeishuDataOperationWithApprovalResult,
  type FeishuDataTablePreviewSyncResult,
  type FeishuEncryptedPayload,
  type FeishuDofeAgentResourceAccessDependencies,
  type FeishuDofeAgentResourceAccessValidationResult,
  type FeishuExternalChannelDocumentInput,
  type FeishuExternalChannelDocumentSyncResult,
  type FeishuExternalDataTableInput,
  type FeishuExternalDataTableSyncResult,
  type FeishuEventHeader,
  type FeishuEventPayload,
  type FeishuHealthCheckResult,
  type FeishuScopeReadiness,
  type FeishuInboundDispatchStatus,
  type FeishuInboundProcessResult,
  type FeishuInboundRecordResult,
  type FeishuLarkCliOperationKind,
  type FeishuLarkCliOperationManifest,
  type FeishuLarkCliOperationManifestResourceGrant,
  type FeishuLarkCliResourceGrant,
  type FeishuLarkCliRuntimeDiagnostic,
  type FeishuLarkCliRuntimeReadinessStatus,
  type FeishuAgentStatusCardStatus,
  type FeishuApprovalCardActionPayload,
  type FeishuCallbackContextValidationResult,
  type FeishuCardActionCallbackResult,
  type FeishuChannelAutoProvisionPolicy,
  type FeishuChannelAutoProvisionResult,
  type FeishuChatMemberSnapshot,
  type FeishuChatDescriptor,
  type FeishuExternalGuestActor,
  type FeishuExternalGuestDecision,
  type FeishuExternalParticipantPolicy,
  type ReadFeishuThreadBindingInput,
  type RecordFeishuThreadBindingInput,
  type FeishuOutboundAttachmentPayload,
  type FeishuOutboundAttachmentRef,
  type FeishuOutboundErrorInfo,
  type FeishuOutboundMessagePolicyResult,
  type FeishuOutboxDrainResult,
  type FeishuOutboxProcessResult,
  type FeishuLarkCliResultManifestOperationSummary,
  type FeishuRuntimeDataOperationRequestApplySummary,
  type FeishuRuntimeDataOperationRequestManifestEntry,
  type FeishuRuntimeDataOperationRequestsManifest,
  type FeishuRuntimeToolIdentityRequirement,
  type FeishuPlainCredentials,
  type FeishuResourceBindingScopeValidationResult,
  type FeishuResourceBindingValidationResult,
  type FeishuResourceDescriptorBindingValidationResult,
  type FeishuResourceMetadataSnapshot,
  type FeishuResourceMetadataSyncResult,
  type FeishuTenantAccessTokenResult,
  type FeishuUrlVerificationPayload,
  type FeishuWebSocketEventProcessorDependencies,
  type FeishuWebSocketWorkerDependencies,
  type FeishuWebSocketWorkerError,
  type FeishuWebSocketWorkerHandle,
  type FeishuWebSocketWorkerSupervisorHandle,
  type FeishuWebSocketWorkerIntegrationSummary,
  type FeishuWebSocketWorkerMetrics,
  type FeishuWebSocketWorkerSession,
  type FeishuWebSocketWorkerSessionFactory,
  type FeishuWebSocketWorkerSessionFactoryInput,
  type FeishuWebSocketWorkerSummary,
  type RotateFeishuAgentBotCredentialsInput,
  type UpdateFeishuAgentBotPolicyInput,
} from "./providers/feishu/index.ts";
